CREATE DATABASE gymEscorpion;
USE gymEscorpion;

CREATE TABLE Estado(
idEstados INT PRIMARY KEY NOT NULL auto_increment,
Estado VARCHAR(45) NULL
);

CREATE TABLE Usuario(
idUsuario INT PRIMARY KEY NOT NULL auto_increment,
idEstado INT NULL AUTO_INCREMENT,
Usuario VARCHAR(45) NULL,
Nombre VARCHAR(45) NULL,
fechaCreacion DATETIME NULL,
pass VARCHAR(45) NULL,
FOREIGN KEY (idEstado) REFERENCES Estado(idEstado)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Socio(
idSocio INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
idEstado INT NOT NULL,
fechaCreacion DATETIME NULL,
Nombre VARCHAR(45) NULL,
Paterno VARCHAR(45) NULL,
Materno VARCHAR(45) NULL,
Tel VARCHAR(45) NULL,
Observaciones VARCHAR(500) NULL,
idUsuarioCreo INT NULL,
FOREIGN KEY (idEstado) REFERENCES Estado(idEstado) 
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (idUsuarioCreo) REFERENCES Usuario(idUsuario)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Sucursal(
idSucursal INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
direccion VARCHAR(45),
Nombre VARCHAR(45),
Tel VARCHAR(10),
idUsuario INT NOT NULL,
miembros INT NULL
);

CREATE TABLE Membresia(
idMembresia INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
Nombre VARCHAR(45) NULL,
idEstado INT NULL,
fechaCreacion DATETIME NULL,
Precio DECIMAL (8, 2) NULL,
idUsuarioCreo INT NULL,
meses INT NULL COMMENT 'meses de la membresia',
horaInicio TIME NULL COMMENT 'hora que comienza la membresia para horarios especiales',
horaFinal TIME NULL COMMENT 'hora en que termina la membresia para horarios especiales',
FOREIGN KEY (idEstado) REFERENCES Estado(idEstado)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (idUsuarioCreo) REFERENCES Usuario(idUsuario)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SocioMembresia(
idSocioMembresia INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
idEstado INT NULL,
fechaCreacion DATETIME NULL,
idUsuarioCreo INT NULL,
idSocio INT NULL,
idMembresia INT NULL,
Precio DECIMAL (8,2) NULL,
fechaInicioMembresia DATETIME NULL,
FOREIGN KEY (idEstado) REFERENCES Estado (idEstado)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (idUsuarioCreo) REFERENCES Usuario(idUsuario)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (idSocio) REFERENCES Socio(idSocio)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (idMembresia) REFERENCES Membresia (idMembresia)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Entrada(
idEntrada INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
idEstado INT NULL DEFAULT 1,
fechaCreacion DATETIME NULL,
idUsuarioCreo INT NULL,
Total DECIMAL (8, 2) NULL,
FOREIGN KEY (idEstado) REFERENCES Estado (idEstado)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (idUsuarioCreo) REFERENCES Usuario(idUsuario)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Salida(
idSalida INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
idEstado INT NULL,
fechaCreacion DATETIME NULL,
total DECIMAL(8, 2) NULL,
idUsuarioCreo INT NULL,
FOREIGN KEY (idEstado) REFERENCES Estado (idEstado) 
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (idUsuario) REFERENCES Usuario (idUsuario)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE DetalleSalida(
idDetalleSalida INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
idProducto INT NULL,
precioUnitario DECIMAL(8, 2) NULL,
idSalida INT NULL,
FOREIGN KEY (idProducto) REFERENCES Producto (idProducto)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (idSalida) REFERENCES Salida (idSalida)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE DetalleEntrada(
idDetalleEntrada INT NOT NULL AUTO_INCREMENT,
idProducto INT NULL,
CostoUnitario DECIMAL(8, 2) NULL,
idEntrado INT NULL,
idDetalleSalida INT NULL,
FOREIGN KEY (idProducto) REFERENCES Producto (idProducto)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (idEntrada) REFERENCES Entrada (idEntrada)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (idDetalleSalida) REFERENCES DetalleSalida (idDetalleSalida)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Registro(
idRegistro INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
idSocio INT NULL,
fechaCreacion DATETIME NULL,
FOREIGN KEY (idSocio) REFERENCES Socio (idSocio)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Visita(
idVisita INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
idSocio INT NULL,
fechaCreacion DATETIME NULL,
precioVisita DECIMAL(8, 2) NULL,
FOREIGN KEY (idSocio) REFERENCES Socio (idSocio)
ON DELETE CASCADE ON UPDATE CASCADE
);